# This is a basic workflow to help you get started with Actions

name: SSH Test

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  perform_ci:
    runs-on: [windows-2022, windows-2019]
    steps:
      - name: Setup SSH keys to pull prebuilt repo
        uses: shimataro/ssh-key-action@v2.7.0
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Attempt to checkout prebuilt repo
        shell: bash
        run: |
          GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone --verbose --depth=1 git@github.com:ferdlestier/parquet.git

