name: SSH Test 2

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  perform_ci:
    strategy:
      matrix:
        runs-on: [windows-2022, windows-2019]

    runs-on: ${{ matrix.runs-on }}
    
    steps:
      - name: Attempt to checkout prebuilt repo
        shell: bash
        run: git --version
